### ISSUE TITLE
Having issues waiting for images to be loaded from groups 

### ISSUE THREAD

**Issue by amprodes** [sarfraznawaz2005/whatspup#11]
HI bro, when people send images the code get blocked until all images in the group chat window get loaded, did you had the same issue? do you know how to fix it? this is the part of the code that give me a timeout error;

`lastMessageGlobal : async function readLastOtherPersonMessage(page,name) {
 
      	let message = '';

	      //let name = await this.currentUser(page);
	    
	      if (!name) {
	        return false;
	      } 

       	//scroll last message
 		await page.evaluate((selector) => {
            try {
				 document.querySelector(selector).scrollIntoView({behavior: 'smooth',block:'end'});  
			} catch (err) { 
	            console.log(err); 
  			}  
		}, selector.last_message); 
 		
 		 
      // read last message sent by other user
      message = await page.evaluate((selector) => {

        let nodes = document.querySelectorAll(selector);
        let el = nodes[nodes.length - 1];  

        if (!el) {
          return '';
        }
 

       let picNodes = el.querySelectorAll("img[src*='blob']");
       let isPicture = picNodes[picNodes.length - 1];

       if (isPicture) {
         return 'Picture Message';
       }

        // check if it is gif message
       let gifNodes = el.querySelectorAll("div[style*='background-image']");
       let isGif = gifNodes[gifNodes.length - 1];

       if (isGif) {
         return 'Gif Message';
       }

        // check if it is video message
        let vidNodes = el.querySelectorAll(".video-thumb");
        let isVideo = vidNodes[vidNodes.length - 1];

        if (isVideo) {
          return 'Video Message';
        }

        // check if it is voice message
        let audioNodes = el.querySelectorAll("audio");
        let isAudio = audioNodes[audioNodes.length - 1];

        if (isAudio) {
          return 'Voice Message';
        }

        // check if it is emoji message
        let emojiNodes = el.querySelectorAll("div.selectable-text img.selectable-text");
        let isEmoji = emojiNodes[emojiNodes.length - 1];

        if (isEmoji) { 
 			
 			var emoArray = [];
        	var imgEmoji = 'https://web.whatsapp.com'+document.querySelector('._2DV1k').getAttribute('src'); 
        	var imgLocal = './public/images/emoji/88179f049c0d1d26c823d2954ecb54a7_w_e1854-64.png'; 

        	emoArray = ['emoji',imgEmoji,imgLocal];

          	return emoArray;
        }

        // text message
        nodes = el.querySelectorAll('span.selectable-text');
        el = nodes[nodes.length - 1];

        return el ? el.innerHTML : '';

      }, selector.last_message);

		//if message is array lets prepare it to be an string
		if(Array.isArray(message) == true && message[0] == "emoji"){

	          	message = await this.getEmoji(message);
	          	
	    }
	    
    	//get ligatures
    	var ligatureName		= await this.ligatures(page,name);
      	var ligatureMessage 	= await this.ligatures(page,message);
      	let user 				= await this.currentUser(page);
      //load from session
      last_received_message = ssn.last_received_message;

      if (message && user == name) {
        if (last_received_message || ssn.messagesCount == 0) {
          if (Array.isArray(message) == false && last_received_message != message) {

            ssn.last_received_message = message;
 
            this.print(ligatureName + ": " + ligatureMessage, config.received_message_color); 
            return ligatureMessage;

          }
        }
        else {
          ssn.last_received_message = message; 
          ssn.messagesCount = (ssn.messagesCount + 1);
          console.log('count: ',ssn.messagesCount);
          return ligatureMessage;
        }

      }
    }`

I have changed the code a little bit to adapt it to my apps need ... please help.

**Comment by sarfraznawaz2005** [comment]
I checked but could not replicate the issue more so with modified code therefore closing this.
