### ISSUE TITLE
Hold Shift + Enter Key

### ISSUE THREAD

**Issue by devdigitalrepublic** [sarfraznawaz2005/whatspup#12]
Is there a way to send shift + enter?

This is useful to create newlines in messages

**Comment by sarfraznawaz2005** [comment]
Not currently but I will add this once I have time. PR is also welcome. Thx

**Comment by devdigitalrepublic** [comment]
Instead of using the type to type a message, can I select the text field and send the whole message?

**Comment by sarfraznawaz2005** [comment]
You will need to look into puppeteer docs and customize the code as per your needs. Alternatively, you can write whole message in notepad for example and paste in whatsapp and then press ENTER to send whole message.

**Comment by sarfraznawaz2005** [comment]
I've added the above code but it seems Control Shirft settings has to be configured in CLI application itself.
