### ISSUE TITLE
Session in headless

### ISSUE THREAD

**Issue by breadpanz** [sarfraznawaz2005/whatspup#14]
The session seems working since it's not asking for QR code again, instead, it shows the image below.

![image](https://user-images.githubusercontent.com/45379896/54263369-a61aa900-45ab-11e9-974d-5b129264592a.png)

**Comment by sarfraznawaz2005** [comment]
Two suggestions:

Make sure you have latest dependencies installed. Run `npm update`, this might update chrome browser used

When window is open and you see above screenshot, press Ctrl + Shift + R to discard cache.

**Comment by breadpanz** [comment]
I'm working on linux server so, the second solution will not work on me. i solved this by removing the tmp file and create a new instance of it. but i don't think that this is the best solution for this problem since i keep scanning the QR code again every time i run it.
