### ISSUE TITLE
Forcing empty cache and hard reload

### ISSUE THREAD

**Issue by yeikiu** [sarfraznawaz2005/whatspup#16]
I´ve achieved a login without showing Chromes window here: https://github.com/yeikiu/waar but keep getting the annoying `Google Chrome 36+` error on random moments. When it does by clicking right click on refresh and choosing `Force empty cache and hard reload`it then shows the QR. You think we can trigger that from within puppeteer as a fallback startegy?

**Comment by sarfraznawaz2005** [comment]
This seems to be problem with Whatsapp web, it happens sometimes even if you use latest version of it, they need to fix it. I would suggest make sure you are using latest version of puppeteer.
