### ISSUE TITLE
Timeout 30S

### ISSUE THREAD

**Issue by MathieuRS1** [sarfraznawaz2005/whatspup#3]
Hi,

I have 30 seconds timeout error with "pupeteer" after "Initializating...".

On MacOS.

Any problem ?

**Comment by sarfraznawaz2005** [comment]
How are you starting it ?

**Comment by MathieuRS1** [comment]
Hi,

Yes it's ok now, thanks :) (Bad username)

However, I can't close the Chrome window.

Mathieu
