### ISSUE TITLE
Not work in invisible/headless mode

### ISSUE THREAD

**Issue by nicobytes** [sarfraznawaz2005/whatspup#4]
when headless is true, not work why? is an issue from puppeteer?

I try run 'web.whatsapp.com' and take screenshot http://i.cubeupload.com/RmJXwC.png with headless mode

**Comment by sarfraznawaz2005** [comment]
yes it is chrommimum issue, ref https://github.com/GoogleChrome/puppeteer/issues/921

**Comment by nicobytes** [comment]
OK thanks but Do you know any solution for this? @sarfraznawaz2005
