### ISSUE TITLE
Do not work on mac

### ISSUE THREAD

**Issue by Alvan-Judi** [sarfraznawaz2005/whatspup#5]
It almost work on mac but it's stuck at "initialisation...".

Also, in the phone app the connexion is name Windows 8.1 while I'm on mac.

**Comment by sarfraznawaz2005** [comment]
Try re-starting it, sometimes on first load it takes time.

If it still doesn't work, try updating user agent value that you are using on line 84:

     await page.setUserAgent('Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3264.0 Safari/537.36');

And uncomment debug line on line 92:

    //debug(page);

When you uncomment, it will generate `screen.png` file in same folder of whatspup, you can check what that screenshot contains when it is trying to connect.

**Comment by sarfraznawaz2005** [comment]
@Alvan-Judi turned out whatsapp had made dom changes. I have updated the selector.js file so you need to update and hopefully now it should work on mac too.

**Comment by TravelTrader** [comment]
Is there a solution for macOS?
It didn't work for me, too.

And how can I de-install `node.js` and `puppeteer/chromium`?
Thanks.
